### ISSUE TITLE
Add OONI Mobile App in Install section of website

### ISSUE THREAD

**Issue by agrabeli** [TheTorProject/ooni-web#116]
We should add OONI's Mobile App in the Install section of the website: https://ooni.torproject.org//install/

**Comment by anadahz** [comment]
Is this resolved?
It seems that there are 2 links with the OONI mobile application in the install
[section](https://ooni.torproject.org//install/) of the OONI's website.

**Comment by hellais** [comment]
Yes this can be closed.
