### ISSUE TITLE
PGP key appears to have expired on March 23rd, 2017

### ISSUE THREAD

**Issue by dimitris-t** [TheTorProject/ooni-web#128]
Page at https://github.com/TheTorProject/ooni-web/blob/master/themes/ooni/layouts/section/about.html (https://ooni.torproject.org/about/) says the PGP key expired on March 23rd, 2017. The same key is quoted in https://github.com/TheTorProject/ooni-web/blob/master/themes/ooni/layouts/index.html (https://ooni.torproject.org).

Also, I cannot seem to find the actual key anywhere but perhaps this is just me.

**Comment by darkk** [comment]
Expiration date was updated and uploaded to keyservers, try `gpg --recv-key 6B2943F00CB177B7` to update it.

```
pub   4096R/6B2943F00CB177B7 2016-03-23 [expires: 2018-03-26]
uid                          OONI - Open Observatory of Network Interference <contact@openobservatory.org>
uid                          OONI - Open Observatory of Network Interference <contact@ooni.io>
sub   4096R/8EBD2087374399AB 2016-03-23 [expires: 2018-03-26]
```

**Comment by darkk** [comment]
Thanks for pointing out that website did not reflect the update, closing as it's #129 now :-)
