### ISSUE TITLE
OONI Run v2 dashboard: non-admin form Firefox issue

### ISSUE THREAD

**Issue by jbonisteel** [TheTorProject/ooni-web#1548]
I was testing the form as a non-admin user and it doesn't seem to work in Firefox. 

I suspect the issue is with the Author's email field. In Firefox, that field is not automatically populated with my email address. It is greyed out and I cannot manually enter my email address either. 

After filling out the rest of the fields and hitting 'generate link' - nothing happens. 

It works as expected in Chrome

**Comment by majakomel** [comment]
I wasn't able to reproduce this one, perhaps you can test once more @jbonisteel to confirm issue still persists on your side?

**Comment by jbonisteel** [comment]
Yeah I can no longer reproduce this issue so I will consider it closed!
