### ISSUE TITLE
update-site.sh should block on travis completion

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-web#170]
As noticed by @agrabeli if you don't wait until travis completes building the new website, but run `make publish-update` then you don't get the latest version, but you get instead the n-1 version.

`update-site.sh` should wait until travis has done it's job before doing it's business.

This can maybe be done by polling: https://api.travis-ci.org/repos/TheTorProject/ooni-web/builds.

cc @darkk

**Comment by darkk** [comment]
> run `make publish-update`

There is no such target in the Makefile anymore :) But that's valid point, process may be improved, machine may wait for another machine. Another important points is that LDAP password should be asked before entering wait loop, otherwise the person will be distracted by something.

**Comment by hellais** [comment]
> There is no such target in the Makefile anymore :)

Hehhe, I was going by memory. s/publish-update/whatever you run to publish on ooni.torproject.org/

> Another important points is that LDAP password should be asked before entering wait loop, otherwise the person will be distracted by something.

For sure, that is why I was suggesting the wait loop is done inside of the `update-site.sh` script that is uploaded to the machine, so it will actually be waiting while it's running as the `ooni` user.
