### ISSUE TITLE
Layout width bug on Android

### ISSUE THREAD

**Issue by darkk** [TheTorProject/ooni-web#79]
The website is not using full screen width in Android Chrome (portrait orientation, album orientation is OK.
Screenshot:
![photo_2016-11-08_22-01-13](https://cloud.githubusercontent.com/assets/21046/20112876/6a77b2e4-a607-11e6-90e4-bf7ab0b16584.jpg)

**Comment by hellais** [comment]
I believe this should have been fixed by @p1g30n, can you confirm?

**Comment by hellais** [comment]
I believe this is fixed. Closing.
