### ISSUE TITLE
Add docker file to reproducibly build the site

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-web#92]
We should have a `Dockerfile` that allows us to build the website with a known good version of hugo and has everything setup properly to do it.

The running of the dockerfile should be instrumented from the `Makefile`.

**Comment by darkk** [comment]
It's non-trivial to build same blob for https://ooni.github.io/ and https://ooni.torproject.org/ due to baseUrl being hardcoded into the webpage body. So two branches should be built: one for ooni.github.io and another one for ooni.tpo.

**Comment by anadahz** [comment]
Partly implemented in: https://github.com/TheTorProject/ooni-web/pull/134

**Comment by darkk** [comment]
I think, current Travis build documented in [tarvis.yml](https://github.com/TheTorProject/ooni-web/blob/master/.travis.yml) and [suggested workflow](https://github.com/TheTorProject/ooni-web/blob/master/.assets/ooni.io.png) are good enough to close this ticket.
